apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: adition
  name: adproxy-account

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: adition
  name: pod-list-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: adition
  name: pod-list-role-binding
subjects:
- kind: ServiceAccount
  name: adproxy-account
roleRef:
  kind: Role
  name: pod-list-role
  apiGroup: rbac.authorization.k8s.io
