apiVersion: v1
kind: Service
metadata:
  namespace: adition
  name: adproxy-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: adproxy
  ports:
  - port: 80
    targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: adition
  name: adproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adproxy
  template:
    metadata:
      labels:
        app: adproxy
    spec:
      serviceAccountName: adproxy-account
      containers:
      - name: adproxy
        image: my-adproxy:v1
        ports:
        - containerPort: 80
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
          # To flush stdout into the logs asap.
        - name: PYTHONUNBUFFERED
          value: "1"
