apiVersion: v1
kind: Service
metadata:
  namespace: adition
  name: db-svc
spec:
  type: ClusterIP
  selector:
    app: database
  ports:
  - port: 80
    targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: adition
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: my-database:v1
        ports:
        - containerPort: 80
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
